import type { TreeEntry } from "@startup/github";

import { MAX_FILE_BYTES } from "../limits";
import { MAX_PATH_LENGTH } from "../walkthrough-document";
import { parseGitAttributes } from "./gitattributes";

// The files that never matter to a new engineer. See "Dropped Files" in
// docs/specs/repo-onboarding-core.md.

export type DropReason =
  | "symlink"
  | "submodule"
  | "too_large"
  | "long_path"
  | "lockfile"
  | "generated"
  | "binary"
  | "vendored";

export interface KeptFile {
  readonly path: string;
  readonly size: number;
}

export interface Listing {
  /** Files, symbolic links, and submodules GitHub listed. Directories are not counted. */
  readonly listed: number;
  /** Files that remain after dropping, in listing order. */
  readonly kept: KeptFile[];
}

const LOCKFILES = new Set([
  "package-lock.json",
  "npm-shrinkwrap.json",
  "pnpm-lock.yaml",
  "go.sum",
  "packages.lock.json",
  "Package.resolved",
  "gradle.lockfile",
]);

// Build output and caches. Any directory with one of these names.
const GENERATED_DIRECTORIES = new Set([
  "dist",
  "build",
  ".next",
  ".nuxt",
  ".svelte-kit",
  ".output",
  ".turbo",
  ".parcel-cache",
  "coverage",
  "__pycache__",
]);

const GENERATED_NAMES = [
  /\.min\.(?:js|mjs|cjs|css)$/i,
  /\.map$/i,
  // Protocol buffers and gRPC.
  /\.pb\.(?:go|cc|h|swift|dart|rs)$/,
  /_pb2(?:_grpc)?\.pyi?$/,
  /_(?:grpc_)?pb\.(?:js|ts|d\.ts)$/,
  /\.pb\.gw\.go$/,
  /\.generated\.\w+$/,
  /\.g\.dart$/,
];

const VENDORED_DIRECTORIES = new Set([
  "vendor",
  "third_party",
  "third-party",
  "node_modules",
  "bower_components",
  "jspm_packages",
]);

const BINARY_EXTENSIONS = new Set([
  // Images
  "png", "jpg", "jpeg", "gif", "bmp", "ico", "icns", "webp", "avif", "tif", "tiff", "psd", "heic", "svg",
  // Fonts
  "woff", "woff2", "ttf", "otf", "eot",
  // Audio and video
  "mp3", "wav", "ogg", "flac", "aac", "m4a", "mp4", "mov", "avi", "mkv", "webm", "m4v",
  // Archives and packages
  "zip", "tar", "gz", "tgz", "bz2", "xz", "zst", "7z", "rar", "jar", "war", "whl", "gem", "nupkg", "deb", "rpm",
  // Compiled objects and executables
  "o", "obj", "a", "lib", "so", "dylib", "dll", "exe", "class", "pyc", "pyo", "wasm", "bin", "dat",
  // Documents and databases
  "pdf", "doc", "docx", "xls", "xlsx", "ppt", "pptx", "sqlite", "sqlite3", "db", "lockb",
]);

/**
 * Drops the files that never matter from GitHub's listing. `attributes` is the
 * root `.gitattributes`, if the repository has one.
 */
export function filterListing(entries: readonly TreeEntry[], attributes: string | null): Listing {
  const linguist = attributes ? parseGitAttributes(attributes) : null;
  const files = entries.filter((entry) => entry.type !== "directory");

  return {
    listed: files.length,
    kept: files.flatMap((entry) => {
      const size = entry.size ?? 0;
      return dropReason(entry, linguist) ? [] : [{ path: entry.path, size }];
    }),
  };
}

/** Why a listed entry is dropped, or `null` when it is kept. */
export function dropReason(
  entry: TreeEntry,
  linguist: ReturnType<typeof parseGitAttributes> | null = null,
): DropReason | null {
  if (entry.type === "symlink") return "symlink";
  if (entry.type === "submodule") return "submodule";
  if (entry.path.length > MAX_PATH_LENGTH) return "long_path";

  const segments = entry.path.split("/");
  const name = segments[segments.length - 1]!;
  const directories = segments.slice(0, -1);
  const extension = name.includes(".") ? name.slice(name.lastIndexOf(".") + 1).toLowerCase() : "";

  if (directories.some((directory) => VENDORED_DIRECTORIES.has(directory))) return "vendored";
  if (LOCKFILES.has(name) || /\.lock(?:b|file)?$/i.test(name)) return "lockfile";
  if (directories.some((directory) => GENERATED_DIRECTORIES.has(directory))) return "generated";
  if (GENERATED_NAMES.some((pattern) => pattern.test(name))) return "generated";
  if (BINARY_EXTENSIONS.has(extension)) return "binary";

  const marked = linguist?.(entry.path);
  if (marked?.vendored) return "vendored";
  if (marked?.generated) return "generated";

  if ((entry.size ?? 0) > MAX_FILE_BYTES) return "too_large";
  return null;
}

const GENERATED_HEADER_LINES = 5;

const GENERATED_HEADERS = [
  /@generated\b/,
  /\bDO NOT EDIT\b/,
  /\bauto-?generated\b/i,
  /\bautomatically generated\b/i,
  /\b(?:this|the) (?:file|code) (?:is|was|has been) (?:auto-?)?generated\b/i,
  /^\W*generated by\b/i,
];

/**
 * Why a file is dropped once its contents are read: `binary` when it holds a
 * NUL byte, `generated` when its first lines say it is generated, or `null`.
 */
export function contentDropReason(bytes: Uint8Array): "binary" | "generated" | null {
  if (bytes.includes(0)) return "binary";

  const head = new TextDecoder().decode(bytes.subarray(0, 2_048));
  const lines = head.split(/\r?\n/, GENERATED_HEADER_LINES);
  if (lines.some((line) => GENERATED_HEADERS.some((pattern) => pattern.test(line)))) return "generated";
  return null;
}
