import { describe, expect, it } from "vitest";

import { GitHubRateLimitError } from "@startup/github";
import type { GenerateObjectRequest, GenerationClient } from "@startup/generation";

import { CANDIDATE_LIMIT, SCORED_FILE_LIMIT } from "../limits";
import { FIXTURE_COMMIT, FIXTURE_MARKER, fakeGitHub, type FakeRepository } from "../testing/github";
import { walkthroughDocumentSchema } from "../walkthrough-document";
import { AnalysisFailure, type AnalysisStep } from "./errors";
import { runAnalysis, type AnalysisDependencies } from "./run";
import type { WriterOutput } from "./walkthrough";

const MINUTE = 60_000;

const widget: FakeRepository = {
  owner: "acme",
  name: "widget",
  description: "Serves widgets.",
  files: {
    "README.md": "# Widget",
    "package.json": "{}",
    "src/index.ts": "export {};",
    "src/server/routes.ts": "export const routes = [];",
    "test/routes.test.ts": "test();",
    "pnpm-lock.yaml": "lockfileVersion: 9",
    "assets/logo.png": "png",
    "vendor/lib.js": "lib",
    "gen/client.ts": "client",
    "src/looks-like-text.ts": new Uint8Array([0x61, 0x00, 0x62]),
    "src/generated.ts": "// Code generated by a tool. DO NOT EDIT.\nexport {};",
  },
  entries: [{ path: "docs/link", type: "symlink", size: undefined }],
};

function setup(repositories: FakeRepository[] = [widget], overrides: Partial<AnalysisDependencies> = {}) {
  const github = fakeGitHub(repositories);
  github.fail("readFile"); // no failures; keeps the call list readable
  const sleeps: number[] = [];
  const deps: AnalysisDependencies = {
    github: github.client,
    decision: null,
    generation: null,
    now: () => 0,
    sleep: async (ms) => {
      sleeps.push(ms);
    },
    ...overrides,
  };
  const progress: { step: AnalysisStep } = { step: "start" };
  const run = (name = "widget") =>
    runAnalysis(
      { owner: "acme", name, commitSha: FIXTURE_COMMIT },
      deps,
      { signal: new AbortController().signal, deadline: 15 * MINUTE, progress },
    );
  return { github, deps, sleeps, progress, run };
}

async function failure(promise: Promise<unknown>): Promise<AnalysisFailure> {
  const error = await promise.then(
    () => {
      throw new Error("expected a failure");
    },
    (caught: unknown) => caught,
  );
  expect(error).toBeInstanceOf(AnalysisFailure);
  return error as AnalysisFailure;
}

describe("runAnalysis", () => {
  it("drops what never matters, ranks the rest, and builds the basic walkthrough", async () => {
    const { github, run } = setup();
    const withAttributes = github.repositories.get("acme/widget")!;
    Object.assign(withAttributes.files, { ".gitattributes": "gen/** linguist-generated\n" });

    const { coverage, walkthrough } = await run();

    // 12 files and a symbolic link; dropped: the lockfile, the image, the
    // vendored file, the linguist-generated file, the link, and, once read,
    // the binary and the generated file.
    expect(coverage).toEqual({ listed: 13, dropped: 7, unscored: 0, localOnly: 6 });
    expect(walkthroughDocumentSchema.parse(walkthrough)).toEqual(walkthrough);
    expect(walkthrough.kind).toBe("basic");
    expect(walkthrough.summary).toEqual([[{ type: "text", text: "Serves widgets." }]]);
    expect(walkthrough.keyFiles.map((file) => file.path)).toEqual([
      "README.md",
      "package.json",
      "src/index.ts",
      "src/server/routes.ts",
      ".gitattributes",
      "test/routes.test.ts",
    ]);
    expect(walkthrough.readingOrder.map((entry) => entry.path)).toEqual([
      "README.md",
      "src/index.ts",
      "package.json",
      ".gitattributes",
      "src/server/routes.ts",
      "test/routes.test.ts",
    ]);
    expect(walkthrough.directories).toEqual([
      { heading: { type: "path", kind: "directory", path: "src", text: "src/" }, description: [{ type: "text", text: "2 files" }] },
      { heading: { type: "path", kind: "directory", path: "test", text: "test/" }, description: [{ type: "text", text: "1 file" }] },
    ]);
    expect(JSON.stringify(walkthrough)).not.toContain(FIXTURE_MARKER);
  });

  it("checks visibility, then lists, reads .gitattributes, and downloads once", async () => {
    const { github, run } = setup();

    await run();

    expect(github.calls).toEqual([
      "getRepository acme/widget",
      "getTree acme/widget",
      "readFile acme/widget",
      "readFiles acme/widget",
    ]);
  });

  it("says when the repository has no description", async () => {
    const { run } = setup([{ ...widget, description: null }]);

    const { walkthrough } = await run();

    expect(walkthrough.summary).toEqual([[{ type: "text", text: "The repository has no description on GitHub." }]]);
  });

  it("chooses 300 files from 1,000 by local signals", async () => {
    const files = Object.fromEntries(Array.from({ length: 1_000 }, (_, index) => [`src/m${index}.ts`, `m${index}`]));
    const { github, run } = setup([{ owner: "acme", name: "big", files }]);
    let requested = 0;
    const readFiles = github.client.readFiles;
    github.client.readFiles = (owner, name, commit, paths, options) => {
      requested = Array.from(paths).length;
      return readFiles(owner, name, commit, paths, options);
    };

    const { coverage, walkthrough } = await run("big");

    expect(requested).toBe(CANDIDATE_LIMIT);
    expect(coverage).toEqual({ listed: 1_000, dropped: 0, unscored: 1_000 - SCORED_FILE_LIMIT, localOnly: SCORED_FILE_LIMIT });
    expect(walkthrough.keyFiles).toHaveLength(15);
  });

  it("scores fewer than 300 when candidates fail the content checks", async () => {
    // The 200 highest-ranked candidates, by local signals, are binary.
    const files: Record<string, string | Uint8Array> = {};
    for (let index = 0; index < 200; index += 1) files[`src/b${index}.ts`] = new Uint8Array([0]);
    for (let index = 0; index < 800; index += 1) files[`test/t${index}.test.ts`] = "test";
    const { run } = setup([{ owner: "acme", name: "mixed", files }]);

    const { coverage } = await run("mixed");

    expect(coverage).toEqual({ listed: 1_000, dropped: 200, unscored: 550, localOnly: 250 });
  });

  it("fails as not found when the repository is now private", async () => {
    const { run } = setup([{ ...widget, private: true }]);

    expect((await failure(run())).reason).toBe("not_found");
  });

  it("fails as too large when GitHub cannot list every file", async () => {
    const { run } = setup([{ ...widget, truncated: true }]);

    expect((await failure(run())).reason).toBe("too_large");
  });

  it("fails as nothing to analyze when every file is dropped", async () => {
    const { run } = setup([{ owner: "acme", name: "assets", files: { "logo.png": "png", "yarn.lock": "x" } }]);

    const error = await failure(run("assets"));

    expect(error.reason).toBe("nothing_to_analyze");
    expect(error.coverage).toEqual({ listed: 2, dropped: 2, unscored: 0, localOnly: 0 });
  });

  it("fails as nothing to analyze when every candidate is binary", async () => {
    const { run } = setup([{ owner: "acme", name: "blobs", files: { "a.ts": new Uint8Array([0]) } }]);

    expect((await failure(run("blobs"))).coverage).toEqual({ listed: 1, dropped: 1, unscored: 0, localOnly: 0 });
  });

  it("waits out a GitHub rate limit that resets within a minute", async () => {
    const { github, sleeps, run } = setup();
    github.fail("getTree", new GitHubRateLimitError(new Date(20_000)));

    await run();

    expect(sleeps).toEqual([21_000]);
    expect(github.calls.filter((call) => call.startsWith("getTree"))).toHaveLength(2);
  });

  it("leaves a later GitHub reset to the worker", async () => {
    const { github, sleeps, progress, run } = setup();
    github.fail("readFiles", new GitHubRateLimitError(new Date(10 * MINUTE)));

    await expect(run()).rejects.toBeInstanceOf(GitHubRateLimitError);
    expect(sleeps).toEqual([]);
    expect(progress.step).toBe("download");
  });

  describe("with the writing model", () => {
    const output: WriterOutput = {
      summary: ["Serves widgets from `src/index.ts`."],
      directories: [{ path: "src", description: "Code." }],
      keyFiles: [{ path: "src/index.ts", why: "Starts it." }],
      readingOrder: [{ path: "README.md", reason: "Overview." }],
    };

    function generation(reply: WriterOutput | Error) {
      const requests: GenerateObjectRequest<unknown>[] = [];
      const client: Pick<GenerationClient, "generateObject"> = {
        async generateObject<T>(request: GenerateObjectRequest<T>) {
          requests.push(request as GenerateObjectRequest<unknown>);
          if (reply instanceof Error) throw reply;
          return { output: reply as T, model: "claude-test", fellBack: false, usage: { inputTokens: 1, outputTokens: 1 } };
        },
      };
      return { requests, client };
    }

    it("writes the walkthrough from the top-ranked files", async () => {
      const writer = generation(output);
      const { run } = setup([widget], { generation: writer.client });

      const { walkthrough } = await run();

      expect(walkthrough.kind).toBe("written");
      expect(walkthrough.summary[0]).toContainEqual({ type: "path", kind: "file", path: "src/index.ts", text: "src/index.ts" });
      const content = JSON.parse(writer.requests[0]!.content);
      expect(content.description).toBe("Serves widgets.");
      expect(content.files.map((file: { path: string }) => file.path)).toContain("src/index.ts");
      expect(content.files[0].content).toContain(FIXTURE_MARKER);
    });

    it("fails as writer failed, with the coverage", async () => {
      const { GenerationProviderError } = await import("@startup/generation");
      const { run } = setup([widget], { generation: generation(new GenerationProviderError("status", 500)).client });

      const error = await failure(run());

      expect(error.reason).toBe("writer_failed");
      expect(error.coverage).toMatchObject({ listed: 13 });
    });
  });
});
