import { inTransaction, QUEUES, type JobQueue } from "@startup/jobs";

/** What an `analysis` job carries. Never repository content. */
export interface AnalysisJobData {
  readonly repositoryId: string;
  /** How many times the analysis was re-queued for a GitHub rate limit. */
  readonly rateLimitDeferrals?: number;
  /**
   * Runs of this analysis interrupted under earlier jobs. A re-queue starts a
   * new job, whose retry count starts at 0 again.
   */
  readonly interruptions?: number;
}

export interface AnalysisJob extends AnalysisJobData {
  readonly userId: string;
  /** Generated by the caller and stored on the repository first. */
  readonly jobId: string;
  /** A time, or seconds from now by the job queue's clock. */
  readonly startAfter?: Date | number;
}

type Transaction = Parameters<typeof inTransaction>[0];

/**
 * Sends an `analysis` job inside `tx`, so it is saved, or rolled back, with
 * the repository row that refers to it. The user is the job's group, which
 * lets the worker run one analysis per user at a time.
 */
export async function sendAnalysis(queue: JobQueue, tx: Transaction, job: AnalysisJob): Promise<void> {
  const data: AnalysisJobData = {
    repositoryId: job.repositoryId,
    ...(job.rateLimitDeferrals ? { rateLimitDeferrals: job.rateLimitDeferrals } : {}),
    ...(job.interruptions ? { interruptions: job.interruptions } : {}),
  };

  const id = await queue.send(QUEUES.analysis.name, data, {
    id: job.jobId,
    group: { id: job.userId },
    db: inTransaction(tx),
    ...(job.startAfter !== undefined ? { startAfter: job.startAfter } : {}),
  });

  if (id !== job.jobId) throw new Error("The analysis job was not created.");
}
